"""initial migration

Revision ID: e05123b4ad6b
Revises: 
Create Date: 2022-09-16 19:33:28.861237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e05123b4ad6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.add_column('todo', sa.Column('person_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.create_foreign_key(None, 'todo', 'user', ['person_id'], ['id'])
    op.drop_column('todo', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.create_foreign_key(None, 'todo', 'user', ['user_id'], ['id'])
    op.drop_column('todo', 'person_id')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
